# Site settings
title: Mikey McOrmond
url: "https://mikeymco.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
description: Personal Site & Link Index

# Include .well-known directory for Chrome DevTools
include:
  - .well-known
