# Site settings
title: Mikey McOrmond
description: "Personal Site & Links"
url: "https://mikeymco.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
